### PR TITLE
Login and installations

### PR DESCRIPTION
**Pull request by jeromelebel**
This is based on investigating the website requests.

### CODE REVIEW

**Comment by ukrolelo** [comment]
Very nice ! thank you ! now lets wait for max to come, or somebody can make pypi package and redirect it for a some time :>
Did you tested it? working ok?

**Comment by ukrolelo** [comment]
I have edited airzone-homeassistant from max, but i have this errors when i try to list zones. It is giving None when i list zones from system/site:
2021-08-22 14:06:07 ERROR (SyncWorker_2) [custom_components.airzonecloud.climate] Site(name=Home, status=None)
2021-08-22 14:06:07 ERROR (SyncWorker_2) [custom_components.airzonecloud.climate] System(name=Sistema 2, mode=None, eco=None, velocity=None, airflow=None)
2021-08-22 14:06:07 ERROR (SyncWorker_2) [custom_components.airzonecloud.climate] None
2021-08-22 14:06:07 ERROR (MainThread) [homeassistant.components.climate] Error while setting up airzonecloud platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/airzonecloud/climate.py", line 63, in setup_platform
entities.append(AirzonecloudZone(zone))
File "/config/custom_components/airzonecloud/climate.py", line 76, in __init__
print("init zone {} ({})".format(self.name, self.unique_id))
File "/config/custom_components/airzonecloud/climate.py", line 87, in name
return "{} - {}".format(self._azc_zone.system.name, self._azc_zone.name)
AttributeError: 'NoneType' object has no attribute 'system'

-----
    for site in api.sites:
        _LOGGER.error(site)
        for system in site.systems:
            _LOGGER.error(system)
            # add zones
            for zone in system.zones:
                _LOGGER.error(zone)
                entities.append(AirzonecloudZone(zone))
            # add system to allow grouped update on all sub zones
            entities.append(AirzonecloudSystem(system))

    add_entities(entities)

**Comment by ukrolelo** [comment]
I took and run the code,directly with test.py and this came out.

Device name=Home, status=None, id=xxxxxx, mac=None, pin=None
System name=Sistema 2, mode=None, eco=None, velocity=None, airflow=None
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    zone.name,
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by bvis** [comment]
Hi, do we have any news regarded to this PR? Was it working? Is it there an available package with the changes?

**Comment by ukrolelo** [comment]
> Hi, do we have any news regarded to this PR? Was it working? Is it there an available package with the changes?

https://github.com/max13fr/AirzoneCloud/issues/7#issuecomment-908217084

**Comment by bvis** [comment]
AFAIK your comment is related to the Local API, this is for Cloud, they are different things, isn't it?

**Comment by ukrolelo** [comment]
> AFAIK your comment is related to the Local API, this is for Cloud, they are different things, isn't it?

something is different,something same. Main thing is that its working and no need to rely on cloud/internet

**Comment by mvillarejo** [comment]
Hello,
Can someone confirm this branch works ok with the latest AirZone API that was released 16th of November?
Kind Regards,

**Comment by max13fr** [comment]
Hello,

No unfortunatelly, they changed the objects tree (now it's Installation -> Group -> Device) and call API are all differents.

I'm currently writing an alpha version to use the new API (but my time is lacking as I need to work on free time the night & the weekend).

Max

**Comment by mvillarejo** [comment]
that's good, thanks for it. I'm happy to support you if you want me to do any testing. 
Checked with technical support today and they do not have in mind to have an 'official' home assistant integration, at least is not in their roadmap. The fact that Hass is 'open-source' kind of challenge the integration.
cheers!

**Comment by max13fr** [comment]
Just released the new version using the new Airzone API : https://developers.airzonecloud.com/docs/web-api/

You can try it, just set your email & password in config_test.json then try (inspired by this PR) : 

```
./test.py
```

It should list all your installations, groups and devices.

I close this PR as it's outdated.

Max

**Pull request closed without merging**
